name: React Linting

on: push

jobs:
  lint-react:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install dependencies
      run: |
        npm install
        npm run eslint

     - name: Run ESLint
        run: npx eslint .